### ISSUE TITLE
Please Update this Repository

### ISSUE THREAD

**Issue by 7aman** [persepolisdm/persepolis-windows-package-build#1]
Hi.
This repository is outdated. For example `ffmpeg` is not included. Can you update this repository?  
I am interested in debugging some windows related issues of persepolis as a playground to learn more about python ad javascript (web-extension).  
I had no problem to set up an editable installation of persepolis. I just want to be able make an installer after bug-fixing is completed.

**Comment by mostafaasadi** [comment]
Hi 
as soon as i can on god's will

**Comment by 7aman** [comment]
I mentioned `ffmpeg` is not included. Just to clearify, I am not suggesting its binary must be included. I meant it is missing in `iss` file. I want the latest versions of plain text files and scripts.

**Comment by mostafaasadi** [comment]
I understood

**Comment by mostafaasadi** [comment]
updated https://github.com/persepolisdm/persepolis-windows-package-build/commit/c68534c2ed9c29c6cb8e6c625662419f94f5194e
