### ISSUE TITLE
What are the advantages of "one-file" executable?

### ISSUE THREAD

**Issue by 7aman** [persepolisdm/persepolis-windows-package-build#2]
Hi.  
Persepolis is currently bundled as a one-file executable (pyinstaller output). On each call, first it loads so many files in user temporary directory then launchs main gui. It takes some seconds and also bloats temp directory. Sometimes created temp folder will not clean after exit. It leads to 1GB or more on some cases.  
I made a non "single-file" build. It runs faster and does not need to cache so much file.  
I am just curious to know why you decided to use "single-file"?

**Comment by alireza-amirsamimi** [comment]
Hello
Please review mainwindow.py and persepolis.py and database.py and initialization.py carefully.

**Comment by 7aman** [comment]
OK.  I will.

**Comment by mostafaasadi** [comment]
Thanks for your suggestion
