### ISSUE TITLE
Can we have a compiled .exe file

### ISSUE THREAD

**Issue by tasinone** [persepolisdm/persepolis-windows-package-build#6]
It's very time-consuming to build. So why don't you release a build version? That would be very helpful. Also, deb for linux. 
Please think about it. Not everyone can build.

**Comment by mostafaasadi** [comment]
Hi
it's under building ... :) 
soon.

**Comment by tasinone** [comment]
> Hi it's under building ... :) soon.

Thanks, bro. Also, if possible then add video catch & download feature like IDM. This is one feature that all other download managers lack.

**Comment by mostafaasadi** [comment]
actully we have it now

**Comment by tasinone** [comment]
> actully we have it now

Okay, I hope we get the build version soon.

**Comment by alireza-amirsamimi** [comment]
@tasinone 
You can download the package build from [release page](https://github.com/persepolisdm/persepolis/releases/tag/4.0.1) now.
